### ISSUE TITLE
[Bug] - User using incorrect slash command leaves text behind

### ISSUE THREAD

**Issue by quackersian** [Ian-c-m/little-spender#1]
**Describe the bug**
When trying to use a slash command, if the user uses one not in the server then it shows as text e.g. "/something". See example in get-role channel of BSBSS

**To Reproduce**
Try using a slash command that doesn't exist e.g. "/something"

**Expected behavior**
The incorrect usage should be deleted if it's not a slash command

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Ian-c-m** [comment]
not a bug, and slash commands removed from the bot anyway
